In [12]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

In [13]:
# Read crime data file
f_path = os.path.join("..", "Resources", "Crime_Merged.csv")
crime_merged_df = pd.read_csv(f_path)
crime_merged_df = crime_merged_df[(crime_merged_df["City"] == "Houston") | (crime_merged_df["City"] == "Pasadena") |(crime_merged_df["City"] == "League City") | (crime_merged_df["City"] == "Sugar Land") | (crime_merged_df["City"] == "Conroe") | (crime_merged_df["City"] == "Baytown") | (crime_merged_df["City"] == "Missouri City") | (crime_merged_df["City"] == "Galveston") | (crime_merged_df["City"] == "Texas City") | (crime_merged_df["City"] == "Friendswood")]
crime_merged_df

,City,Year,Population,Violent Crime,Murder,Rape,Robbery,Aggravated Assault,Property Crime,Burglary,Larceny Theft,Motor/Vehicle Theft,Arson
35,Baytown,2012.0,"74,420",247,5.0,15,97,130,"3,684",939,"2,438",307,23.0
115,Conroe,2012.0,"59,856",221,2.0,13,74,132,"2,061",447,"1,501",113,1.0
194,Friendswood,2012.0,"36,965",15,0.0,4,4,7,353,66,274,13,0.0
198,Galveston,2012.0,"49,170",296,2.0,37,118,139,"2,469",517,"1,792",160,12.0
255,Houston,2012.0,"2,177,273","21,610",217.0,665,"9,385","11,343","107,678","26,630","67,978","13,070",754.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4054,League City,2018.0,"105,351",97,3.0,34,18,42,"1,718",218,"1,407",93,3.0
4102,Missouri City,2018.0,"75,863",149,2.0,23,46,78,969,133,767,69,0.0
4150,Pasadena,2018.0,"154,000",711,5.0,93,195,418,"3,773",636,"2,758",379,23.0
4270,Sugar Land,2018.0,"89,790",71,0.0,15,36,20,"1,289",158,"1,075",56,0.0
4287,Texas City,2018.0,"48,774",237,2.0,47,46,142,"1,704",336,"1,245",123,1.0

In [14]:
crime_merged_df["Lat"] = ""
crime_merged_df["Lng"] = ""
crime_merged_df.head()

,City,Year,Population,Violent Crime,Murder,Rape,Robbery,Aggravated Assault,Property Crime,Burglary,Larceny Theft,Motor/Vehicle Theft,Arson,Lat,Lng
35,Baytown,2012.0,"74,420",247,5.0,15,97,130,"3,684",939,"2,438",307,23.0,,
115,Conroe,2012.0,"59,856",221,2.0,13,74,132,"2,061",447,"1,501",113,1.0,,
194,Friendswood,2012.0,"36,965",15,0.0,4,4,7,353,66,274,13,0.0,,
198,Galveston,2012.0,"49,170",296,2.0,37,118,139,"2,469",517,"1,792",160,12.0,,
255,Houston,2012.0,"2,177,273","21,610",217.0,665,"9,385","11,343","107,678","26,630","67,978","13,070",754.0,,

In [15]:
 
                                  
# create a params dict that will be updated with new city each iteration
params = {"key": g_key}

# Loop through the cities_pd and run a lat/long search for each city
for index, row in crime_merged_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    city = row['City']
    state = "TX"
    #print(f"Searching within {city}, {state}...")
    
    # update address key value
    params['address'] = f"{city},{state}"

    # Execute request
    crime_lat_lng = requests.get(base_url, params=params)
    
    # convert response to json
    crime_lat_lng = crime_lat_lng.json()

    # Add resulting lat & lng to their respective columns at the current iteration's row index
    crime_merged_df.loc[index, "Lat"] = crime_lat_lng["results"][0]["geometry"]["location"]["lat"]
    crime_merged_df.loc[index, "Lng"] = crime_lat_lng["results"][0]["geometry"]["location"]["lng"]

# Visualize to confirm lat lng appear
crime_merged_df

,City,Year,Population,Violent Crime,Murder,Rape,Robbery,Aggravated Assault,Property Crime,Burglary,Larceny Theft,Motor/Vehicle Theft,Arson,Lat,Lng
35,Baytown,2012.0,"74,420",247,5.0,15,97,130,"3,684",939,"2,438",307,23.0,29.7355,-94.9774
115,Conroe,2012.0,"59,856",221,2.0,13,74,132,"2,061",447,"1,501",113,1.0,30.3119,-95.4561
194,Friendswood,2012.0,"36,965",15,0.0,4,4,7,353,66,274,13,0.0,29.5294,-95.201
198,Galveston,2012.0,"49,170",296,2.0,37,118,139,"2,469",517,"1,792",160,12.0,29.3013,-94.7977
255,Houston,2012.0,"2,177,273","21,610",217.0,665,"9,385","11,343","107,678","26,630","67,978","13,070",754.0,29.7604,-95.3698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4054,League City,2018.0,"105,351",97,3.0,34,18,42,"1,718",218,"1,407",93,3.0,29.5075,-95.0949
4102,Missouri City,2018.0,"75,863",149,2.0,23,46,78,969,133,767,69,0.0,29.6186,-95.5377
4150,Pasadena,2018.0,"154,000",711,5.0,93,195,418,"3,773",636,"2,758",379,23.0,29.6911,-95.2091
4270,Sugar Land,2018.0,"89,790",71,0.0,15,36,20,"1,289",158,"1,075",56,0.0,29.5984,-95.6226
4287,Texas City,2018.0,"48,774",237,2.0,47,46,142,"1,704",336,"1,245",123,1.0,29.3838,-94.9027

In [16]:
crime_merged_df_2018 = crime_merged_df[(crime_merged_df["Year"] == 2018.0)]
crime_merged_df_2018
#crime_merged_df.dtypes

,City,Year,Population,Violent Crime,Murder,Rape,Robbery,Aggravated Assault,Property Crime,Burglary,Larceny Theft,Motor/Vehicle Theft,Arson,Lat,Lng
3770,Baytown,2018.0,"76,704",288,6.0,38,108,136,"2,678",506,"1,846",326,1.0,29.7355,-94.9774
3843,Conroe,2018.0,"85,534",249,4.0,54,65,126,"1,931",276,"1,479",176,3.0,30.3119,-95.4561
3922,Friendswood,2018.0,"39,990",36,0.0,16,11,9,321,57,247,17,1.0,29.5294,-95.201
3928,Galveston,2018.0,"51,021",257,2.0,63,82,110,"1,790",275,"1,231",284,3.0,29.3013,-94.7977
3986,Houston,2018.0,"2,338,235","25,609",269.0,"1,366","9,773","14,201","96,532","17,108","67,828","11,596",665.0,29.7604,-95.3698
4054,League City,2018.0,"105,351",97,3.0,34,18,42,"1,718",218,"1,407",93,3.0,29.5075,-95.0949
4102,Missouri City,2018.0,"75,863",149,2.0,23,46,78,969,133,767,69,0.0,29.6186,-95.5377
4150,Pasadena,2018.0,"154,000",711,5.0,93,195,418,"3,773",636,"2,758",379,23.0,29.6911,-95.2091
4270,Sugar Land,2018.0,"89,790",71,0.0,15,36,20,"1,289",158,"1,075",56,0.0,29.5984,-95.6226
4287,Texas City,2018.0,"48,774",237,2.0,47,46,142,"1,704",336,"1,245",123,1.0,29.3838,-94.9027

In [17]:
# create variables to store the data we plan to use on our plot

# data to be used for the plotting coordinates
locations = crime_merged_df_2018["Lat","Lng"]

# data to be used to weight the heatmap
rating = crime_merged_df_2018["Violent Crime"]

# create the mapping figure
fig = gmaps.figure()

# create the heatmap layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating)

# add the heatmap layer to the figure
fig.add_layer(heat_layer)

# display the figure
fig

KeyError: ('Lat', 'Lng')